[2024-03-05T20:53:57.375+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-05T20:53:57.379+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-05T20:53:57.380+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-05T20:53:57.388+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-05T20:53:57.391+0000] {standard_task_runner.py:60} INFO - Started process 212 to run task
[2024-03-05T20:53:57.393+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmppj2c8wn3']
[2024-03-05T20:53:57.394+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask download_dataset
[2024-03-05T20:53:57.418+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T20:53:57.444+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-05T20:53:57.460+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-05T20:53:57.461+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-05T20:53:57.461+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh 2022 12']
[2024-03-05T20:53:57.466+0000] {subprocess.py:86} INFO - Output:
[2024-03-05T20:53:57.468+0000] {subprocess.py:93} INFO - 
[2024-03-05T20:53:57.468+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2022/12
[2024-03-05T20:53:57.468+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2022/12
[2024-03-05T20:53:57.469+0000] {subprocess.py:93} INFO - /opt/***/include/download_bike_dataset.sh: 14: wget: Permission denied
[2024-03-05T20:53:57.469+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-05T20:53:57.474+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-05T20:53:57.476+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240305T205357, end_date=20240305T205357
[2024-03-05T20:53:57.483+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task download_dataset (Bash command failed. The command returned a non-zero exit code 1.; 212)
[2024-03-05T20:53:57.525+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T20:53:57.539+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:12:26.474+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:26.479+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:26.479+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-05T21:12:26.487+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-05T21:12:26.490+0000] {standard_task_runner.py:60} INFO - Started process 759 to run task
[2024-03-05T21:12:26.492+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmps00c9coo']
[2024-03-05T21:12:26.493+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask download_dataset
[2024-03-05T21:12:26.519+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:12:26.543+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:26.544+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:26.548+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240305T211226, end_date=20240305T211226
[2024-03-05T21:12:26.555+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task download_dataset ('str object' has no attribute 'strftime'; 759)
[2024-03-05T21:12:26.584+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:12:26.598+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-07T13:45:05.087+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T13:45:05.092+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T13:45:05.093+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-03-07T13:45:05.100+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-07T13:45:05.104+0000] {standard_task_runner.py:60} INFO - Started process 533 to run task
[2024-03-07T13:45:05.106+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmp5fosjt87']
[2024-03-07T13:45:05.107+0000] {standard_task_runner.py:88} INFO - Job 128: Subtask download_dataset
[2024-03-07T13:45:05.135+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 0430cbdaac75
[2024-03-07T13:45:05.166+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T13:45:05.291+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-07T13:45:05.292+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T13:45:05.292+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 01']
[2024-03-07T13:45:05.299+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T13:45:05.301+0000] {subprocess.py:93} INFO - 
[2024-03-07T13:45:05.301+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-07T13:45:05.305+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T13:45:05.306+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T13:45:08.000+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  9 1820k    9  176k    0     0  86015      0  0:00:21  0:00:02  0:00:19 85997100 1820k  100 1820k    0     0   675k      0  0:00:02  0:00:02 --:--:--  675k
[2024-03-07T13:45:08.004+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T13:45:08.047+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv
[2024-03-07T13:45:08.047+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/__MACOSX/._JC-202301-citibike-tripdata.csv
[2024-03-07T13:45:08.221+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv (deflated 84%)
[2024-03-07T13:45:08.222+0000] {subprocess.py:93} INFO - 
[2024-03-07T13:45:08.222+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T13:45:08.222+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T13:45:08.235+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240307T134505, end_date=20240307T134508
[2024-03-07T13:45:08.249+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T13:45:08.259+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-07T14:12:10.811+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T14:12:10.816+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T14:12:10.816+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-03-07T14:12:10.824+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-07T14:12:10.827+0000] {standard_task_runner.py:60} INFO - Started process 1739 to run task
[2024-03-07T14:12:10.829+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpc6wauio1']
[2024-03-07T14:12:10.830+0000] {standard_task_runner.py:88} INFO - Job 189: Subtask download_dataset
[2024-03-07T14:12:10.860+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host 0430cbdaac75
[2024-03-07T14:12:10.889+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T14:12:10.994+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-07T14:12:10.994+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T14:12:10.995+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 01']
[2024-03-07T14:12:11.001+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T14:12:11.002+0000] {subprocess.py:93} INFO - 
[2024-03-07T14:12:11.002+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-07T14:12:11.006+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T14:12:11.006+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T14:12:12.780+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 15 1820k   15  287k    0     0   204k      0  0:00:08  0:00:01  0:00:07  204k100 1820k  100 1820k    0     0  1026k      0  0:00:01  0:00:01 --:--:-- 1026k
[2024-03-07T14:12:12.782+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T14:12:12.823+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv
[2024-03-07T14:12:12.823+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/__MACOSX/._JC-202301-citibike-tripdata.csv
[2024-03-07T14:12:12.995+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv (deflated 84%)
[2024-03-07T14:12:12.996+0000] {subprocess.py:93} INFO - 
[2024-03-07T14:12:12.996+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T14:12:12.996+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T14:12:12.996+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T14:12:13.009+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240307T141210, end_date=20240307T141213
[2024-03-07T14:12:13.048+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T14:12:13.061+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-07T18:16:34.435+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T18:16:34.442+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2024-03-07T18:16:34.442+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-03-07T18:16:34.538+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2022-12-01 00:00:00+00:00
[2024-03-07T18:16:34.543+0000] {standard_task_runner.py:60} INFO - Started process 1228 to run task
[2024-03-07T18:16:34.546+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpw84akmfj']
[2024-03-07T18:16:34.549+0000] {standard_task_runner.py:88} INFO - Job 252: Subtask download_dataset
[2024-03-07T18:16:34.601+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2022-12-01T00:00:00+00:00 [running]> on host a0c898e5643f
[2024-03-07T18:16:34.639+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T18:16:34.661+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-01T00:00:00+00:00'
[2024-03-07T18:16:34.663+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T18:16:34.663+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 01']
[2024-03-07T18:16:34.674+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T18:16:34.678+0000] {subprocess.py:93} INFO - 
[2024-03-07T18:16:34.679+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-07T18:16:34.685+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T18:16:34.685+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T18:16:36.322+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0 1820k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 92 1820k   92 1690k    0     0  1036k      0  0:00:01  0:00:01 --:--:-- 1036k100 1820k  100 1820k    0     0  1111k      0  0:00:01  0:00:01 --:--:-- 1111k
[2024-03-07T18:16:36.326+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T18:16:36.387+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv
[2024-03-07T18:16:36.388+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/01/__MACOSX/._JC-202301-citibike-tripdata.csv
[2024-03-07T18:16:36.564+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv (deflated 84%)
[2024-03-07T18:16:36.565+0000] {subprocess.py:93} INFO - 
[2024-03-07T18:16:36.565+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T18:16:36.565+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/01/JC-202301-citibike-tripdata.csv.zip
[2024-03-07T18:16:36.566+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T18:16:36.580+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20221201T000000, start_date=20240307T181634, end_date=20240307T181636
[2024-03-07T18:16:36.603+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T18:16:36.618+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
